### ISSUE TITLE
フォロワーユーザーの詳細ページを作る

### ISSUE THREAD

**Issue by kdmgs110** [kdmgs110/Tweet-Analyser#19]

**Comment by kdmgs110** [comment]
# メリット・目的

- フォロワーの詳細情報を保存しておくことができるので、毎回APIのエンドポイントにアクセスする必要がなくなる
- フォロワーの一時点の情報を保存しておけるので、その差分が取れるとどういうアクションを取った結果どういう結果になったのかが理解できる

# 実装方法

- DB1 フォロワー数のうつりかわりを保存できるテーブル
- DB2 その時のスナップショットのフォロワーデータを保存できるCSVエクスポート機能、およびインポート機能
- DB3 DB2でいいけど、ある一時点のフォロワー数が毎回更新されるDB、これの利用目的としては、
ref #3 で毎回フォロワーの値をAPIでとってくるとすぐにrate-limitに達してしまうため、最新版のデータを更新できるようにしておいて、中で処理をさせたいから。

フォロワーユーザーを、更新したスナップショットごとに比較できるとよい。
昨日は何人で、おとといは何人だったみたいな。
それを保存する統計データと、

**Comment by kdmgs110** [comment]
/you で
`更新する`をクリックすると、最新のフォロワー情報が取得される。
フォロワー情報を取得すると、まずDB1に以下の値が更新される。

ID | CREATED_AT | FOLLOWER_COUNT
-- | -- | --

次にフォロワーの中の詳細情報が、${DB1のID}.csvとして、\csv\followers\1.csv　のような形で保存される

**Comment by kdmgs110** [comment]
#3 からフォロワーを取得するときは、CSVの中でも最新の番号のものを読みこんで、その中のユーザーIDを全取得、かつリスト化するという処理にすることになるとおもう。

**Comment by kdmgs110** [comment]
ユーザーIDからデータを見るときはここがよさそう。

https://syncer.jp/Web/API/Twitter/REST_API/GET/users/show/

**Comment by kdmgs110** [comment]
userID指定でこんな感じで帰ってくるらしい。


json
```
{
id:1528352858
id_str:1528352858
name:あらゆ
screen_name:arayutw
location:東京都足立区
profile_location:null
description:SYNCERというサイトを運用しています。掲示板→ https://t.co/OAIDbACF3N
url:https://t.co/lW3GYq8sQl
entities:{
url:{
urls:[
0:{
url:https://t.co/lW3GYq8sQl
expanded_url:https://syncer.jp/
display_url:syncer.jp
indices:[
0:0
1:23
]
}
]
}
description:{
urls:[
0:{
url:https://t.co/OAIDbACF3N
expanded_url:https://forum.syncer.jp/
display_url:forum.syncer.jp
indices:[
0:26
1:49
]
}
]
}
}
protected:false
followers_count:1417
friends_count:563
listed_count:114
created_at:Tue Jun 18 17:28:51 +0000 2013
favourites_count:4456
utc_offset:32400
time_zone:Asia/Tokyo
geo_enabled:true
verified:false
statuses_count:34824
lang:ja
status:{
created_at:Wed Jan 18 09:36:48 +0000 2017
id:821652553255571500
id_str:821652553255571458
text:murashun.jpが人気。
truncated:false
entities:{
hashtags:[]
symbols:[]
user_mentions:[]
urls:[]
}
source:<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>
in_reply_to_status_id:821652327794966500
in_reply_to_status_id_str:821652327794966530
in_reply_to_user_id:1528352858
in_reply_to_user_id_str:1528352858
in_reply_to_screen_name:arayutw
geo:null
coordinates:null
place:null
contributors:null
is_quote_status:false
retweet_count:1
favorite_count:0
favorited:false
retweeted:false
lang:ja
}
contributors_enabled:false
is_translator:false
is_translation_enabled:true
profile_background_color:2660A1
profile_background_image_url:http://pbs.twimg.com/profile_background_images/632205394824183808/FIL3S4z4.png
profile_background_image_url_https:https://pbs.twimg.com/profile_background_images/632205394824183808/FIL3S4z4.png
profile_background_tile:false
profile_image_url:http://pbs.twimg.com/profile_images/631038167416619008/7xfGAEwp_normal.png
profile_image_url_https:https://pbs.twimg.com/profile_images/631038167416619008/7xfGAEwp_normal.png
profile_banner_url:https://pbs.twimg.com/profile_banners/1528352858/1484730634
profile_link_color:D36015
profile_sidebar_border_color:F2E195
profile_sidebar_fill_color:FFF7CC
profile_text_color:0C3E53
profile_use_background_image:false
has_extended_profile:false
default_profile:false
default_profile_image:false
following:false
follow_request_sent:false
notifications:false
translator_type:regular
suspended:false
needs_phone_verification:false
}
```

**Comment by kdmgs110** [comment]
https://stackoverflow.com/questions/35384358/how-to-open-my-files-in-data-folder-with-pandas-using-relative-path

相対パスで行けそう

```
Try

import pandas as pd
pd.read_csv("../data_folder/data.csv")
```

**Comment by kdmgs110** [comment]
こんな感じかな
あとはread_csv抜きでデータフレームオブジェクトを作る。、

```
def exportFollowerCSV(created_at, followers_ids):
    """
    フォロワー数更新時に、フォロワー数の詳細データをCSVにエクスポートします
    """
    try:
        for user_id in follower_ids:
            followerCount = getFollowersCount(user_id)
            followingCount = getFollowingsCount(user_id)
            se = pandas.Series([userid, followers, followings],['userid','followers','followings'])
            df = df.append(se, ignore_index=True)
        df.to_csv("../csv/followers/{}.csv".format(created_at))
```

**Comment by kdmgs110** [comment]
フォロワー・フォロー数を更新をクリックした際に以下のエラー

```
kdmgs110@DESKTOP-4HHEO95:/mnt/c/workspace/pydev/tweet-analyser$ python3 app.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 337-201-509
127.0.0.1 - - [07/Apr/2018 11:12:39] "GET /index HTTP/1.1" 200 -
127.0.0.1 - - [07/Apr/2018 11:12:42] "GET /you HTTP/1.1" 200 -
127.0.0.1 - - [07/Apr/2018 11:12:44] "GET /you/followers HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/workspace/pydev/tweet-analyser/app.py", line 66, in followers
    return render_template("followers.html")
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: followers.html
```

**Comment by kdmgs110** [comment]
you/followersにリダイレクトされているので、それを変える必要がある。
正しくはyou/followers/update

**Comment by kdmgs110** [comment]
次はこのエラー
```
File b'../csv/default/followers.csv' does not exist
127.0.0.1 - - [07/Apr/2018 11:38:53] "GET /you/followers/update HTTP/1.1" 302 -
127.0.0.1 - - [07/Apr/2018 11:38:53] "GET /you HTTP/1.1" 200 -
```

**Comment by kdmgs110** [comment]
ラーメン食ったらここ直す。
```
[ERROR] CSVのエクスポートに失敗しました：name 'follower_ids' is not defined
127.0.0.1 - - [07/Apr/2018 11:41:59] "GET /you/followers/update HTTP/1.1" 302 -
127.0.0.1 - - [07/Apr/2018 11:41:59] "GET /you HTTP/1.1" 200 -
 * Detected change in '/mnt/c/workspace/pydev/tweet-analyser/app.py', reloading
 * Restarting with stat
```

**Comment by kdmgs110** [comment]
なんかエラー起きてる

```
[ERROR] CSVのエクスポートに失敗しました：[Errno 2] No such file or directory: '../csv/followers/2018/04/07 13:58:25.csv.csv'
127.0.0.1 - - [07/Apr/2018 13:58:25] "GET /you/followers/update HTTP/1.1" 302 -
127.0.0.1 - - [07/Apr/2018 13:58:25] "GET /you HTTP/1.1" 200 -
```

**Comment by kdmgs110** [comment]
エクスポートしてるところが死んでる。

```
kdmgs110@DESKTOP-4HHEO95:/mnt/c/workspace/pydev/tweet-analyser$ tree
.
├── README.md
├── __pycache__
│   └── config.cpython-35.pyc
├── app.py
├── config.py
├── csv
│   ├── default
│   │   └── followers.csv
│   └── followers
├── db
│   └── database.db
├── image
│   ├── index.PNG
│   ├── keyword.PNG
│   ├── rateLimit.PNG
│   ├── show.PNG
│   └── stats.PNG
├── result.csv
├── sql.py
└── templates
    ├── addQuery.html
    ├── followings.html
    ├── home.html
    ├── includes
    │   └── _navbar.html
    ├── layout.html
    ├── query.html
    ├── queryList.html
    └── yourProfile.html
```

**Comment by kdmgs110** [comment]
```
def exportFollowerCSV(created_at, followers_ids):
    """
    フォロワー数更新時に、フォロワー数の詳細データをCSVにエクスポートします
    user_id,user_name,followings_count,followers_count
    """
    df = pd.DataFrame(columns=["user_id","user_name","followings_count","followers_count"])
    try:
        for user_id in followers_ids:
            user_name = getUserName(user_id)
            print (user_name)
            followings_count = getFollowingsCount(user_id)
            followers_count = getFollowersCount(user_id)
            se = pd.Series(
                [user_id, user_name, followings_count, followers_count],
                ["user_id","user_name","followings_count","followers_count"]
                )
            df = df.append(se, ignore_index=True)
        df.to_csv("../csv/followers/{}.csv".format(created_at))
    except Exception as e:
        print("[ERROR] CSVのエクスポートに失敗しました：{}".format(e))
```

**Comment by kdmgs110** [comment]
160人くらいデータ取ると、いったんrate-limitになる。

```
155  891114794660397056   Twitter              133              37
156  803834513231151105   Twitter              273             266
157  974603805978324993   Twitter               91              33
158           407528353   Twitter              417              72
159  979125977979568128   Twitter               25              61
160  922154220903477249   Twitter              844              58

[161 rows x 4 columns]
[ERROR] CSVのエクスポートに失敗しました：[{'code': 88, 'message': 'Rate limit exceeded'}]
127.0.0.1 - - [07/Apr/2018 14:26:51] "GET /you/followers/update HTTP/1.1" 302 -
127.0.0.1 - - [07/Apr/2018 14:26:51] "GET /you HTTP/1.1" 200 -
```

**Comment by kdmgs110** [comment]
失敗している。

```
2675          2937961896   Twitter             2288            1679
2676          2880896198   Twitter              195             172
2677          4547064049   Twitter              189             249
2678          1622169314   Twitter            88817          121500
2679  722676495160893440   Twitter             1522            1406
2680           105426209   Twitter              356            1654
2681          1068370165   Twitter             4884            4150
2682          4655402082   Twitter              388             186
2683  734694621784117248   Twitter              648             307
2684          2412543019   Twitter             2378            1840
2685           737565014   Twitter             2437            2566
2686          3714604292   Twitter             1820            1000
2687            77202768   Twitter             3217             810
2688  721320555735941121   Twitter               41               5
2689          3241582550   Twitter            24225           24812
2690          2346433118   Twitter              635             556
2691          2821422156   Twitter              853             449
2692          3286500588   Twitter              280             344
2693  725681236778180608   Twitter             1285             947
2694           116182228   Twitter             1943             823
2695          2702863171   Twitter               20              22
2696           232181133   Twitter            70051           82534
2697          1261223143   Twitter              670             579
2698  709260308020211712   Twitter              799             390

[2699 rows x 4 columns]
[Errno 2] No such file or directory: '../csv/followers/2018/04/07 14:47:38.csv'
127.0.0.1 - - [07/Apr/2018 17:32:58] "GET /you/followers/update HTTP/1.1" 302 -
127.0.0.1 - - [07/Apr/2018 17:32:58] "GET /you HTTP/1.1" 200 -
 * Detected change in '/mnt/c/workspace/pydev/tweet-analyser/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 337-201-509
127.0.0.1 - - [07/Apr/2018 18:01:50] "GET /addQuery HTTP/1.1" 200 -
127.0.0.1 - - [07/Apr/2018 18:01:51] "GET /you HTTP/1.1" 200 -
^Ckdmgs110@DESKTOP-4HHEO95:/mnt/c/workspace/pydev/tweet-analyser$ ^C
kdmgs110@DESKTOP-4HHEO95:/mnt/c/workspace/pydev/tweet-analyser$
```

to_csv()の問題っぽい。

```
kdmgs110@DESKTOP-4HHEO95:/mnt/c/workspace/pydev/tweet-analyser$ ipython
Python 3.5.2 (default, Sep 14 2017, 22:51:06)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: ls
README.md*    app.py*     csv/  image/       sql.py*
__pycache__/  config.py*  db/   result.csv*  templates/

In [2]: import pandas as pd

In [3]: df = pd.DatFrame(columns=["hoge", "piyo", "fuga"])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-ebd24f7ea5d2> in <module>()
----> 1 df = pd.DatFrame(columns=["hoge", "piyo", "fuga"])

AttributeError: module 'pandas' has no attribute 'DatFrame'

In [4]: df = pd.DataFrame(columns=["hoge", "piyo", "fuga"])

In [5]: df.to_csv("csv/default/test.csv")

In [6]: tree
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-7a1e081e78d4> in <module>()
----> 1 tree

NameError: name 'tree' is not defined

In [7]: exit()
kdmgs110@DESKTOP-4HHEO95:/mnt/c/workspace/pydev/tweet-analyser$ tree
.
├── README.md
├── __pycache__
│   └── config.cpython-35.pyc
├── app.py
├── config.py
├── csv
│   ├── default
│   │   ├── followers.csv
│   │   └── test.csv
│   └── followers
├── db
│   └── database.db
├── image
│   ├── index.PNG
│   ├── keyword.PNG
│   ├── rateLimit.PNG
│   ├── show.PNG
│   └── stats.PNG
├── result.csv
├── sql.py
└── templates
    ├── addQuery.html
    ├── followings.html
    ├── home.html
    ├── includes
    │   └── _navbar.html
    ├── layout.html
    ├── query.html
    ├── queryList.html
    └── yourProfile.html
```

**Comment by kdmgs110** [comment]
```python:app.py
def exportFollowerCSV(created_at, followers_ids):
    """
    フォロワー数更新時に、フォロワー数の詳細データをCSVにエクスポートします
    user_id,user_name,followings_count,followers_count
    """
    df = pd.DataFrame(columns=["user_id","user_name","followings_count","followers_count"])
    for user_id in followers_ids:
        try:
            user_name = getUserName(user_id)
            print (user_name)
            followings_count = getFollowingsCount(user_id)
            followers_count = getFollowersCount(user_id)
            se = pd.Series(
                [user_id, user_name, followings_count, followers_count],
                ["user_id","user_name","followings_count","followers_count"]
                )
            df = df.append(se, ignore_index=True)
            print(df)
        except Exception as e:
            print("[ERROR] データの取得に失敗しました：{}".format(e))
            print("[INFO] 15分間待機します")
            time.sleep(60 * 15)
            continue
    df.to_csv("../csv/followers/{}".format(created_at))
```

これを

```
 df.to_csv("csv/followers/{}".format(created_at))
```
に変換すれば大丈夫そう。

**Comment by kdmgs110** [comment]
あとフォロワー数が今が2706なのに、取得できているのが2698
になっているので、たぶんエラーが起こっている回数分の処理を抜かしている可能性がある。
これをどう解決したらよいのかちょっと迷う。

```
2698  709260308020211712   Twitter              799             390
```

**Comment by kdmgs110** [comment]
flaskでクエリ投げてあげると特定のユーザーが出てきたらうれしい。
フォロワー数・フォロー数でソートできて、選択してリムーブとか。
chartjsあたりで実装できるとよい。

https://code.i-harness.com/ja/q/17bd283
