### ISSUE TITLE
自動いいね機能を修正する

### ISSUE THREAD

**Issue by kdmgs110** [kdmgs110/Tweet-Analyser#21]

**Comment by kdmgs110** [comment]
```
[INFO]likeレコードを追加しました。user_id:mendoublogger
[INFO]いいね数: 1
[INFO]likeレコードを追加しました。user_id:allschool_navi
[INFO]いいね数: 2
[INFO]likeレコードを追加しました。user_id:withup_kaito
[INFO]いいね数: 3
[ERROR]いいねに失敗しました: [{'code': 139, 'message': 'You have already favorited this status.'}]
127.0.0.1 - - [07/Apr/2018 18:24:05] "GET /like/9/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/workspace/pydev/tweet-analyser/app.py", line 80, in like
    like_count = likeTweets(tweets, id)
  File "/mnt/c/workspace/pydev/tweet-analyser/app.py", line 253, in likeTweets
    if e["code"] == 139:
TypeError: 'TweepError' object is not subscriptable
127.0.0.1 - - [07/Apr/2018 18:24:05] "GET /like/9/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [07/Apr/2018 18:24:05] "GET /like/9/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Apr/2018 18:24:05] "GET /like/9/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [07/Apr/2018 18:24:06] "GET /like/9/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [07/Apr/2018 18:24:06] "GET /like/9/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by kdmgs110** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr">Tweepyのエラー処理でステータスコードごとに条件分岐する方法、リファレンス見てもなかった。これを参考にして実装してみる。<br><br>Tweepyでエラーにならないように例外処理する<a href="https://t.co/9VuZhelYcX">https://t.co/9VuZhelYcX</a></p>&mdash; Dai (@never_be_a_pm) <a href="https://twitter.com/never_be_a_pm/status/982703339379900417?ref_src=twsrc%5Etfw">April 7, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

```
except TweepError, e:
...   if e.response and e.response.status == 404:
...     print 'error'
```
