### ISSUE TITLE
WEB上から直接CRONを設定できるようにする

### ISSUE THREAD

**Issue by kdmgs110** [kdmgs110/Tweet-Analyser#24]
ref #23 で、CUI上でいいねを実行することができるようになったので、GUI上からCRON設定することができるようにしたい。じゃないとUIで完結しないから。

**Comment by kdmgs110** [comment]
Python用のcrontab パッケージ
http://stackabuse.com/scheduling-jobs-with-python-crontab/

**Comment by kdmgs110** [comment]
ということで、一応FLASKでUI上で定期実行を仕込ませることはできそうではある。
UIの部分をさくっと作って、実際の処理のところを作りたい。

**Comment by kdmgs110** [comment]
ログファイルとかどうしようかなぁ。作成時に実行するコマンドのログファイルをlogs/実行コマンド.logで残しておく感じがよいのかな。

**Comment by kdmgs110** [comment]
とりあえずUIを実装する

keyword/index => キーワード一覧
keyword/show => キーワード詳細

ここまではある。

keyword/indexから、keyword/editで編集ページに飛べるようにして、そこでcrontabを設定できるようにしようかな。
keyword/indexからは現在有効になっているcrontabと、そのcrontabが有効か否かを判定できればよい。さくっとUIで実装する。

**Comment by kdmgs110** [comment]
app.pyを修正

```python:app.py
@app.route("/edit/<id>")
def editQuery(id):
    res = selectQueryById(id)
    return render_template('query.html', res = res)
```

```python:
# SQL関係のメソッド
def selectQueryById(queryId):
    conn = sqlite3.connect(DATABASE)
    c = conn.cursor()
    insertSQL = "SELECT * FROM query WHERE id = ?"
    res = c.execute(insertSQL, [queryId])
    c.close()
    return res
```

**Comment by kdmgs110** [comment]
crontabに関しては別のDBで保持したほうがよさそう。

**Comment by kdmgs110** [comment]
DB:crontab


id | name | crontab | is_enabled
-- | -- | -- | --
1 | #progate | * * * * * | TRUE


こんな感じになるかな。

**Comment by kdmgs110** [comment]
DB: query

id | query | cron_id
-- | -- | --
1 | #progate | 1.00



と思ったけど、別に分けなくてもよいかも
これで十分。

id | name | crontab | is_enabled
-- | -- | -- | --
1 | #progate | * * * * * | TRUE

**Comment by kdmgs110** [comment]
ということでDBに関してはもとのqueryテーブルでこれでいく。

id | name | crontab | is_enabled
-- | -- | -- | --
1 | #progate | * * * * * | TRUE

**Comment by kdmgs110** [comment]
カラムを追加しなきゃ。

**Comment by kdmgs110** [comment]
こう変えればDB変更できそう。

```python:
create_query_db_sql = "CREATE TABLE IF NOT EXISTS query (id integer PRIMARY KEY, query text, cron_tab text, is_enabled boolean)"
c.execute(create_query_db_sql)
```

**Comment by kdmgs110** [comment]
あとから追加する場合はDBの初期化をしないといけないのね。

**Comment by kdmgs110** [comment]
とりあえず初期化

```
kdmgs110@DESKTOP-4HHEO95:/mnt/c/workspace/pydev/tweet-analyser$ sqlite3 db/database.db
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> select * from query;
10|#Progate
13|#Railsチュートリアル
14|#note
15|#Aidemy
16|#Qiita
sqlite> drop table query;
sqlite> select * from query;
Error: no such table: query
```

**Comment by kdmgs110** [comment]
/index にアクセスしたときにエラー

```
sqlite3.OperationalError
sqlite3.OperationalError: no such table: query
```
たぶんSQLでテーブル作成されるコードよりも前にHTML部分が呼び出されてしまい、その結果queryというテーブルがないと言われているはず。結局DBかかわらないところからアクセスした後に再度戻ったらうまくいった。

**Comment by kdmgs110** [comment]
```
create_query_db_sql = "CREATE TABLE IF NOT EXISTS query (id integer PRIMARY KEY, query text, cron_tab text, is_enabled boolean)"
```
で、キーワードを追加しようと思ったら以下のエラー
```
Traceback (most recent call last):
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/workspace/pydev/tweet-analyser/app.py", line 95, in addQuery
    insertQuery(query, cron)
  File "/mnt/c/workspace/pydev/tweet-analyser/app.py", line 185, in insertQuery
    c.execute(insertSQL, [query, crontab])
sqlite3.OperationalError: table query has no column named crontab
```

そりゃそうだ、cron_tabだもんな名前。

**Comment by kdmgs110** [comment]
アンチパターン
* 命名規則で死んだ

**Comment by kdmgs110** [comment]
よく考えたらcrontabのon offも編集画面から決められる必要がある。

**Comment by kdmgs110** [comment]
トグルボタンを作れるbootstrap、現状すごくダサいので修正が必要

http://www.bootstraptoggle.com/

**Comment by kdmgs110** [comment]
editから受け取った値をPOSTリクエストで受け付けて、そこからtrueの値をDBに保存できるようにする。

**Comment by kdmgs110** [comment]
![crontab](https://user-images.githubusercontent.com/13186896/38648370-d7f023f2-3e2b-11e8-89da-439e44a46305.PNG)

**Comment by kdmgs110** [comment]
![crontab](https://user-images.githubusercontent.com/13186896/38648504-82c1deec-3e2c-11e8-9bbb-b4fb659a7797.gif)

**Comment by kdmgs110** [comment]
* /editでPOSTを受け取る
 * crontab 
 * is_enabled
* DBに保存する
* /queryListにリダイレクトする

**Comment by kdmgs110** [comment]
Handling GET and POST in same Flask view

https://stackoverflow.com/questions/42018603/handling-get-and-post-in-same-flask-view

```
import flask
app = flask.Flask('your_flask_env')

@app.route('/register', methods=['GET', 'POST'])
def register():
    if flask.request.method == 'POST':
        username = flask.request.values.get('user') # Your form's
        password = flask.request.values.get('pass') # input names
        your_register_routine(username, password)
    else:
        # You probably don't have args at this route with GET
        # method, but if you do, you can access them like so:
        yourarg = flask.request.args.get('argname')
        your_register_template_rendering(yourarg)
```

**Comment by kdmgs110** [comment]
こっちか

http://flask.pocoo.org/docs/0.12/quickstart/
```
from flask import request

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        do_the_login()
    else:
        show_the_login_form()
```

**Comment by kdmgs110** [comment]
# TODO
edit.htmlのpostをedit/idにリダイレクトさせる

**Comment by kdmgs110** [comment]
edit/1 POST

```
Method Not Allowed
The method is not allowed for the requested URL.
```

**Comment by kdmgs110** [comment]
methodsの指定忘れてた。

**Comment by kdmgs110** [comment]
DBが初期化されていないので、初期化するためにDB消す
```
kdmgs110@DESKTOP-4HHEO95:/mnt/c/workspace/pydev/tweet-analyser$ sqlite3  db/database.db
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> select * from query;
1|#テックキャンプ|* * * * * |
2|#Qiita|* * * * * |
sqlite>
```

**Comment by kdmgs110** [comment]
sqlite3にはboolean型が存在しないので、integerで0・1でやる必要があるらしい。
http://wada811.blogspot.com/2012/10/sqlearning-sqlite-datatype-constraint.html

**Comment by kdmgs110** [comment]
処理イメージ

・もし値を挿入されたときにqueryとcrontabが書かれていたら、その値をcrontabに書き込む
・もしis_enabled=ONになったら、設定したcrontabをコメントアウトする
・もしis_enabled=FALSEになったら、そのcrontabをコメントインする

TODO:
- <crontab>python3 <path>/autoLike.py <query>を実行できるような処理を作成する
- コメントイン・コメントアウトの処理を実装する

**Comment by kdmgs110** [comment]
`もし値を挿入されたときにqueryとcrontabが書かれていたら、その値をcrontabに書き込む`

これはaddQueryされたタイミングで書き込んで、コメントアウトする感じかな。

```
from crontab import CronTab

query = "#Qiita"

cron = CronTab(user=True)  
job = cron.new(command= dir + 'python3 autoLike.py' + query)
job.minute.every(1)
cron.write() 
```

**Comment by kdmgs110** [comment]
```
import os
cwd = os.getcwd()
print(cwd)
```
これでできるらしい。

**Comment by kdmgs110** [comment]
from crontab import CronTab
import os
cwd = os.getcwd()
query = "#Qiita"

cron = CronTab(user=True)  
job = cron.new(command= "python3 "cwd + '/autoLike.py ' + query)
job.minute.every(1)
cron.write() 
```
これでできそう。あとはコメントアウトする方法。

**Comment by kdmgs110** [comment]
これっぽい

```
job.enable()
job.enable(False)
False == job.is_enabled()
```

**Comment by kdmgs110** [comment]
コメントも追加したい。query IDが後から操作しやすそう

**Comment by kdmgs110** [comment]
```
cron.new(command='my command', comment='my comment')  
```
