### ISSUE TITLE
AttributeError: 'CronRange' object has no attribute 'enable'

### ISSUE THREAD

**Issue by kdmgs110** [kdmgs110/Tweet-Analyser#29]
builtins.AttributeError
AttributeError: 'CronRange' object has no attribute 'enable'

**Comment by kdmgs110** [comment]
```
Traceback (most recent call last):
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/workspace/pydev/tweet-analyser/app.py", line 105, in addQuery
    addCronTab(query, cron)
  File "/mnt/c/workspace/pydev/tweet-analyser/app.py", line 402, in addCronTab
    job.enable(False)
AttributeError: 'CronRange' object has no attribute 'enable'
```
