### ISSUE TITLE
キーワード削除時に、crontabを削除しておきたい。

### ISSUE THREAD

**Issue by kdmgs110** [kdmgs110/Tweet-Analyser#31]
ref #30 crontabのon offはできたので、今度は削除もできるようにしたいところ。

**Comment by kdmgs110** [comment]
最初にjupyter notebookで頑張るよ！
できたらここにコミットする！

**Comment by kdmgs110** [comment]
うぜぇ

```
127.0.0.1 - - [17/Apr/2018 23:13:53] "GET /delete/2/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/mnt/c/workspace/pydev/tweet-analyser/app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 337-201-509
query:None
127.0.0.1 - - [17/Apr/2018 23:14:11] "GET /delete/2/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kdmgs110/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/workspace/pydev/tweet-analyser/app.py", line 106, in deleteQuery
    deleteCronTab(id)
  File "/mnt/c/workspace/pydev/tweet-analyser/app.py", line 438, in deleteCronTab
    for job in jobs:
  File "/usr/local/lib/python3.5/dist-packages/crontab.py", line 412, in find_command
    elif command in job.command:
TypeError: 'in <string>' requires string as left operand, not sqlite3.Cursor
```

**Comment by kdmgs110** [comment]
`TypeError: 'in <string>' requires string as left operand, not NoneType`
と出てて、

```
def deleteCronTab(id):
    query = getQueryFromQueryId(id)
    print("query:{}".format(query))
    cron = CronTab(user=True)
    jobs = cron.find_command(query)
    for job in jobs:
        cron.remove(job)
        cron.write()
        print("[INFO] 以下のJOBを削除しました:{}".format(query))
```
の
`print("query:{}".format(query))` 
がNoneType Objectになってるのがまずい。

**Comment by kdmgs110** [comment]
完了。
- ログ出力ができているのかわからないのでログファイルの設定を行えるように、cron側で設定する
- database初期化したときに再起動しなくてもdb initされるようにしたい。before executionみたいな関数なかったっけ
- requirements.txt作らなければ。
